require:
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - "bin/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
  TargetRubyVersion: 3.1

Layout/FirstArgumentIndentation:
  Enabled: false

Layout/LineEndStringConcatenationIndentation:
  EnforcedStyle: indented

Layout/LineLength:
  Max: 120

Layout/MultilineMethodCallIndentation:
  Enabled: false

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented
  # It doesn't seem to work well in our case, so we exclude a couple of false offenses
  Exclude:
    - "lib/organizer/creator.rb"
    - "lib/twitter/rest_client.rb"

Layout/SpaceInsideStringInterpolation:
  Enabled: false

Metrics/AbcSize:
  Max: 18

Metrics/BlockLength:
  Exclude:
    - "**/api/v1/*.rb"
    - "**/api/v2/*.rb"
    - "**/spec/**/*.rb"
    - "**/Rakefile"

Metrics/MethodLength:
  Max: 20

Naming/PredicateName:
  Exclude:
    - "**/entity/*.rb"

RSpec/ExampleLength:
  Max: 15

RSpec/FilePath:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FetchEnvVar:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: no_mixed_keys
  EnforcedShorthandSyntax: consistent

Style/NumericPredicate:
  Enabled: false

Style/RedundantAssignment:
  Enabled: false

Style/StringConcatenation:
  Enabled: false
