version: "3.8"

services:
  api:
    build: .
    image: vlctechhub/api:latest
    volumes:
      - type: bind
        source: .
        target: /app
        consistency: delegated
      - type: volume
        source: bundle
        target: /usr/local/bundle
    tmpfs:
      - /app/tmp:exec
    ports:
      - "5000:5000"
    networks:
      default:
        aliases:
          - api.vlctechhub.local
    environment:
      - RACK_ENV=development
      - PORT=5000
      - MONGODB_URI=mongodb://mongo:27017/vlctechhub-dev
      - TEST_MONGODB_URI=mongodb://mongo:27017/vlctechhub-test
      - SENDGRID_PASSWORD
      - SENDGRID_USERNAME
      - EMAIL_FOR_PUBLICATION
      - EMAIL_FOR_BROADCAST
      - TWITTER_CONSUMER_KEY
      - TWITTER_CONSUMER_SECRET
      - TWITTER_ACCESS_TOKEN
      - TWITTER_ACCESS_SECRET
      - NEW_RELIC_LICENSE_KEY
    depends_on:
      - mongo
    command:
      ["bash", "-c", "(bundle check || bundle install) && rake up"]

  mongo:
    image: mongo:5.0.14
    volumes:
      - type: volume
        source: data
        target: /data/db

volumes:
  data:
  bundle:
