name: Lint

on: [push]

jobs:
  Rubocop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Set up Ruby 3.1.3
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.3
      - name: Set up Rubocop
        run: gem install rubocop -v '~> 1.39.0'
      - name: Set up Rubocop Rspec extension
        run: gem install rubocop-rspec -v '~> 2.15.0'
      - name: Run Rubocop checks
        run: rubocop .

  SyntaxTree:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Set up Ruby 3.1.3
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.3
      - name: Set up SyntaxTree
        run: gem install syntax_tree -v '~> 5.0.1'
      - name: Run SyntaxTree checks
        run: stree check '**/*.rb' '**/*.ru' Rakefile Gemfile Clockfile
