name: Test

on: [push]

jobs:
  RSpec:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Set up Ruby 3.1.3
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.3
      - name: Install dependencies
        run: bundle config set --local without 'production' && bundle install
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: 5.0.14
      - name: Set up environment
        run: rake setenv
      - name: Preparare test data
        run: rake test:prepare
      - name: Run tests
        run: rake test:run
